main: io.github.redpanda4552.SimpleEgg.Main
name: SimpleEgg
version: 0.4.7
author: bdubz4552
description: A plugin to allow the capture and conversion of living entites to spawn eggs.
softdepend: [Vault]
api-version: 1.13

commands:
    simpleegg:
        description: Help command for SimpleEgg
        usage: /simpleegg
        aliases: se

permissions:
    # Global
    SimpleEgg.*:
        children:
            SimpleEgg.passive: true
            SimpleEgg.villager: true
            SimpleEgg.wanderingtrader: true
            SimpleEgg.tameable: true
            SimpleEgg.monster: true
            SimpleEgg.owner-override: true
            SimpleEgg.steal: true
            SimpleEgg.auto-tame: true
            SimpleEgg.use-spawner: true
            SimpleEgg.update-notify: true

    # Admin
    SimpleEgg.update-notify:
        description: capture this mob 
    SimpleEgg.reload:
        description: capture this mob

    # Passive
    SimpleEgg.passive:
        children:
            SimpleEgg.bat: true
            SimpleEgg.chicken: true
            SimpleEgg.cod: true
            SimpleEgg.cow: true
            SimpleEgg.dolphin: true
            SimpleEgg.fox: true
            SimpleEgg.irongolem: true
            SimpleEgg.mushroomcow: true
            SimpleEgg.panda: true
            SimpleEgg.pig: true
            SimpleEgg.polarbear: true
            SimpleEgg.pufferfish: true
            SimpleEgg.rabbit: true
            SimpleEgg.salmon: true
            SimpleEgg.sheep: true
            SimpleEgg.snowman: true
            SimpleEgg.squid: true
            SimpleEgg.tropicalfish: true
            SimpleEgg.turtle: true
    SimpleEgg.bat:
        description: capture this mob
    SimpleEgg.chicken:
        description: capture this mob
    SimpleEgg.cod:
        description: capture this mob
    SimpleEgg.cow:
        description: capture this mob
    SimpleEgg.dolphin:
        description: capture this mob
    SimpleEgg.fox:
        description: capture this mob
    SimpleEgg.irongolem:
        description: capture this mob
    SimpleEgg.mushroomcow:
        description: capture this mob
    SimpleEgg.panda:
        description: capture this mob
    SimpleEgg.pig:
        description: capture this mob
    SimpleEgg.polarbear:
        description: capture this mob
    SimpleEgg.pufferfish:
        description: capture this mob
    SimpleEgg.rabbit:
        description: capture this mob
    SimpleEgg.salmon:
        description: capture this mob
    SimpleEgg.sheep:
        description: capture this mob
    SimpleEgg.snowman:
        description: capture this mob
    SimpleEgg.squid:
        description: capture this mob
    SimpleEgg.tropicalfish:
        description: capture this mob
    SimpleEgg.turtle:
        description: capture this mob

    # Villager
    SimpleEgg.villager:
        description: capture this mob
        
    # Wandering Trader
    SimpleEgg.wanderingtrader:
        description: capture this mob

    # Tameable
    SimpleEgg.tameable:
        description: capture this mob
        children:
            SimpleEgg.cat: true
            SimpleEgg.donkey: true
            SimpleEgg.horse: true
            SimpleEgg.llama: true
            SimpleEgg.mule: true
            SimpleEgg.ocelot: true
            SimpleEgg.parrot: true
            SimpleEgg.skeletonhorse: true
            SimpleEgg.traderllama: true
            SimpleEgg.wolf: true
            SimpleEgg.zombiehorse: true
    SimpleEgg.cat:
        description: capture this mob 
    SimpleEgg.donkey:
        description: capture this mob 
    SimpleEgg.horse:
        description: capture this mob
    SimpleEgg.llama:
        description: capture this mob
    SimpleEgg.mule:
        description: capture this mob
    SimpleEgg.ocelot:
        description: capture this mob
    SimpleEgg.parrot:
        description: capture this mob
    SimpleEgg.skeletonhorse:
        description: capture this mob
    SimpleEgg.traderllama:
        description: capture this mob
    SimpleEgg.wolf:
        description: capture this mob
    SimpleEgg.zombiehorse:
        description: capture this mob

    # Monsters
    SimpleEgg.monster:
        children:
            SimpleEgg.blaze: true
            SimpleEgg.cavespider: true
            SimpleEgg.creeper: true
            SimpleEgg.drowned: true
            SimpleEgg.elderguardian: true
            SimpleEgg.enderman: true
            SimpleEgg.endermite: true
            SimpleEgg.evoker: true
            SimpleEgg.ghast: true
            SimpleEgg.guardian: true
            SimpleEgg.husk: true
            SimpleEgg.magmacube: true
            SimpleEgg.phantom: true
            SimpleEgg.pigzombie: true
            SimpleEgg.pillager: true
            SimpleEgg.ravager: true
            SimpleEgg.shulker: true
            SimpleEgg.silverfish: true
            SimpleEgg.skeleton: true
            SimpleEgg.slime: true
            SimpleEgg.spider: true
            SimpleEgg.stray: true
            SimpleEgg.vex: true
            SimpleEgg.vindicator: true
            SimpleEgg.witch: true
            SimpleEgg.wither: true
            SimpleEgg.witherskeleton: true
            SimpleEgg.zombie: true
            SimpleEgg.zombievillager: true
    SimpleEgg.blaze:
        description: capture this mob
    SimpleEgg.cavespider:
        description: capture this mob
    SimpleEgg.creeper:
        description: capture this mob
    SimpleEgg.drowned:
        description: capture this mob
    SimpleEgg.elderguardian:
        description: capture this mob
    SimpleEgg.enderman:
        description: capture this mob
    SimpleEgg.endermite:
        description: capture this mob
    SimpleEgg.evoker:
        description: capture this mob
    SimpleEgg.ghast:
        description: capture this mob
    SimpleEgg.guardian:
        description: capture this mob
    SimpleEgg.husk:
        description: capture this mob
    SimpleEgg.magmacube:
        description: capture this mob
    SimpleEgg.phantom:
        description: capture this mob
    SimpleEgg.pigzombie:
        description: capture this mob
    SimpleEgg.pillager:
        description: capture this mob
    SimpleEgg.ravager:
        description: capture this mob
    SimpleEgg.shulker:
        description: capture this mob
    SimpleEgg.silverfish:
        description: capture this mob
    SimpleEgg.skeleton:
        description: capture this mob
    SimpleEgg.slime:
        description: capture this mob
    SimpleEgg.spider:
        description: capture this mob
    SimpleEgg.stray:
        description: capture this mob
    SimpleEgg.vex:
        description: capture this mob
    SimpleEgg.vindicator:
        description: capture this mob
    SimpleEgg.witch:
        description: capture this mob
    SimpleEgg.wither:
        description: capture this mob
    SimpleEgg.witherskeleton:
        description: capture this mob
    SimpleEgg.zombie:
        description: capture this mob
    SimpleEgg.zombievillager:
        description: capture this mob

    # Ownership Modifications
    SimpleEgg.owner-override:
        description: capture this mob
    SimpleEgg.steal:
        children:
            SimpleEgg.owner-override: true
    SimpleEgg.auto-tame:
        description: capture this mob
    
    # Other
    SimpleEgg.use-spawner:
        description: capture this mob
