/**
 * This file is part of SimpleEgg, licensed under the MIT License (MIT)
 * 
 * Copyright (c) 2015 Brian Wood
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package io.github.redpanda4552.SimpleEgg.command;

import io.github.redpanda4552.SimpleEgg.SECommand;
import io.github.redpanda4552.SimpleEgg.SimpleEggMain;

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;

public class CSimpleEgg extends SECommand {

	private final ChatColor a = ChatColor.AQUA;
	private final ChatColor b = ChatColor.BLUE;
	
	public CSimpleEgg(SimpleEggMain plugin) {
		super(plugin);
	}
	
	private String[] help = {
		a + "== SimpleEgg v" + plugin.getDescription().getVersion() + " by bdubz4552 ==",
		b + "The alias for " + a + "/simpleegg" + b + " is " + a + "/se" + b + ".",
		b + "/simpleegg capturing",
		b + "/simpleegg horses",
	};
	
	//There isn't really a clean way to do this until I export this text to an external file... So for now, just cringe over it with me.
	private String[] helpCapture = {
		a + "Capturing a mob",
		
		a + "- " + b + "To capture a mob, throw an " + a + "Egg" + b + " at it. In addition, you will need to have " + a + plugin.consumedMaterialAmount +
		" " + plugin.consumedMaterialName + b + " in your inventory. The spawn egg will be dropped where the mob was, and the above mentioned items will be " +
		"removed from your inventory.",
		
		a + "- " + b + "SimpleEgg respects tameable mobs. If you try to capture a mob that is owned by someone else, SimpleEgg will refuse. " +
		"Note that SimpleEgg does not have the ability to detect artificial ownership generated by other plugins, only the true ownership defined " +
		"by vanilla Minecraft.",
				
		a + "- " + b + "If your attemted capture is invalid for some reason, your egg that you threw will be returned."
	};
	
	private String[] helpHorses = {
		a + "SimpleEgg and Horses",
		
		a + "- " + b + "Bukkit/Spigot cannot properly assign a horse's jump and speed values, so SimpleEgg will not handle these properties.",
		
		a + "- " + b + "Bukkit/Spigot may on occasion ignore the age of a horse and spawn in a baby that renders as an adult. You can tell by if adult " +
		"specific features (riding, inventory access, etc) are disabled. The horse is still feedable and will become a true adult with food and/or time."
	};
	
	@Override
	public boolean onCommand(CommandSender sender, Command command, String label, String[] args)
	{
		if (args.length == 0)
		{
			sender.sendMessage(help);
		}
		else if (args.length >= 1)
		{
			if (args[0].equalsIgnoreCase("Capturing"))
			{
				sender.sendMessage(helpCapture);
			}
			else if (args[0].equalsIgnoreCase("Horses"))
			{
				sender.sendMessage(helpHorses);
			}
		}
		return true;
	}

}
